[StreamNativeBlog]
title = "StreamNative Blog"
url = "https://streamnative.io/en/blog/"
entrySelector = "#app .blog-box .blogs-content-list .pass-item>.blogs-right"
titleSelector = ".blogs-list-title"
linkSelector = ".blogs-list-title>a"
