[default]
timeout = 300
waitUntil = "load"

[StreamNativeBlog]
title = "StreamNative Blog"
url = "https://streamnative.io/blogs/"
entrySelector = "#app > div > div:nth-child(2) > div:nth-child(2) > section > div.mb-6.mx-auto"
titleSelector = "a > div > div > div > div.flex-1.flex.flex-col.p-6.pl-10 > div.text-4xl.sn-text-25.sn-text-bold.text-gray-darkest"
linkSelector = "a"
contentSelector = "a"

[BilibiliTech]
title = "幻电物业 - B站技术中心"
url = "https://space.bilibili.com/393183630/article"
entrySelector = "#page-article .main-content .article>.content>.article-wrap>.article-item"
titleSelector = ".s-content>.article-title"
linkSelector = ".s-content>.article-title>a"
contentSelector = ".s-content>.article-con"

[acwifi]
title = "路由器交流-无线路由器使用分享与评测对比"
url = "https://www.acwifi.net/page/1"
entrySelector = "body.blog section.container div.content-wrap div.content article.excerpt.excerpt-one"
titleSelector = "header>h2"
linkSelector = "header>h2>a"
contentSelector = "p.note"

[cnblogs_cmt]
title = "博客园官方博客"
url = "https://www.cnblogs.com/cmt/"
entrySelector = "#mainContent>.forFlow>.day"
titleSelector = ".postTitle"
linkSelector = ".dayTitle>a"
contentSelector = ".postCon"
